#pragma once
/**
* Mapping pressed keys to ids. This is identical to glfw's key mapping.
*/
//Keyboard
#define GWA_KEY_SPACE              32
#define GWA_KEY_APOSTROPHE         39  
#define GWA_KEY_COMMA              44  
#define GWA_KEY_MINUS              45 
#define GWA_KEY_PERIOD             46 
#define GWA_KEY_SLASH              47 
#define GWA_KEY_0                  48
#define GWA_KEY_1                  49
#define GWA_KEY_2                  50
#define GWA_KEY_3                  51
#define GWA_KEY_4                  52
#define GWA_KEY_5                  53
#define GWA_KEY_6                  54
#define GWA_KEY_7                  55
#define GWA_KEY_8                  56
#define GWA_KEY_9                  57
#define GWA_KEY_SEMICOLON          59 
#define GWA_KEY_EQUAL              61  
#define GWA_KEY_A                  65
#define GWA_KEY_B                  66
#define GWA_KEY_C                  67
#define GWA_KEY_D                  68
#define GWA_KEY_E                  69
#define GWA_KEY_F                  70
#define GWA_KEY_G                  71
#define GWA_KEY_H                  72
#define GWA_KEY_I                  73
#define GWA_KEY_J                  74
#define GWA_KEY_K                  75
#define GWA_KEY_L                  76
#define GWA_KEY_M                  77
#define GWA_KEY_N                  78
#define GWA_KEY_O                  79
#define GWA_KEY_P                  80
#define GWA_KEY_Q                  81
#define GWA_KEY_R                  82
#define GWA_KEY_S                  83
#define GWA_KEY_T                  84
#define GWA_KEY_U                  85
#define GWA_KEY_V                  86
#define GWA_KEY_W                  87
#define GWA_KEY_X                  88
#define GWA_KEY_Y                  89
#define GWA_KEY_Z                  90

//Function Keys
#define GWA_KEY_ESCAPE             256
#define GWA_KEY_ENTER              257
#define GWA_KEY_TAB                258
#define GWA_KEY_BACKSPACE          259
#define GWA_KEY_INSERT             260
#define GWA_KEY_DELETE             261
#define GWA_KEY_RIGHT              262
#define GWA_KEY_LEFT               263
#define GWA_KEY_DOWN               264
#define GWA_KEY_UP                 265
#define GWA_KEY_PAGE_UP            266
#define GWA_KEY_PAGE_DOWN          267
#define GWA_KEY_HOME               268
#define GWA_KEY_END                269
#define GWA_KEY_CAPS_LOCK          280
#define GWA_KEY_SCROLL_LOCK        281
#define GWA_KEY_NUM_LOCK           282
#define GWA_KEY_PRINT_SCREEN       283
#define GWA_KEY_PAUSE              284
#define GWA_KEY_F1                 290
#define GWA_KEY_F2                 291
#define GWA_KEY_F3                 292
#define GWA_KEY_F4                 293
#define GWA_KEY_F5                 294
#define GWA_KEY_F6                 295
#define GWA_KEY_F7                 296
#define GWA_KEY_F8                 297
#define GWA_KEY_F9                 298
#define GWA_KEY_F10                299
#define GWA_KEY_F11                300
#define GWA_KEY_F12                301
#define GWA_KEY_F13                302
#define GWA_KEY_F14                303
#define GWA_KEY_F15                304
#define GWA_KEY_F16                305
#define GWA_KEY_F17                306
#define GWA_KEY_F18                307
#define GWA_KEY_F19                308
#define GWA_KEY_F20                309
#define GWA_KEY_F21                310
#define GWA_KEY_F22                311
#define GWA_KEY_F23                312
#define GWA_KEY_F24                313
#define GWA_KEY_F25                314
#define GWA_KEY_KP_0               320
#define GWA_KEY_KP_1               321
#define GWA_KEY_KP_2               322
#define GWA_KEY_KP_3               323
#define GWA_KEY_KP_4               324
#define GWA_KEY_KP_5               325
#define GWA_KEY_KP_6               326
#define GWA_KEY_KP_7               327
#define GWA_KEY_KP_8               328
#define GWA_KEY_KP_9               329
#define GWA_KEY_KP_DECIMAL         330
#define GWA_KEY_KP_DIVIDE          331
#define GWA_KEY_KP_MULTIPLY        332
#define GWA_KEY_KP_SUBTRACT        333
#define GWA_KEY_KP_ADD             334
#define GWA_KEY_KP_ENTER           335
#define GWA_KEY_KP_EQUAL           336
#define GWA_KEY_LEFT_SHIFT         340
#define GWA_KEY_LEFT_CONTROL       341
#define GWA_KEY_LEFT_ALT           342
#define GWA_KEY_LEFT_SUPER         343
#define GWA_KEY_RIGHT_SHIFT        344
#define GWA_KEY_RIGHT_CONTROL      345
#define GWA_KEY_RIGHT_ALT          346
#define GWA_KEY_RIGHT_SUPER        347
#define GWA_KEY_MENU               348

//Mouse Keys
#define GWA_MOUSE_BUTTON_1         0
#define GWA_MOUSE_BUTTON_2         1
#define GWA_MOUSE_BUTTON_3         2
#define GWA_MOUSE_BUTTON_4         3
#define GWA_MOUSE_BUTTON_5         4
#define GWA_MOUSE_BUTTON_6         5
#define GWA_MOUSE_BUTTON_7         6
#define GWA_MOUSE_BUTTON_8         7
#define GWA_MOUSE_BUTTON_LAST      GWA_MOUSE_BUTTON_8
#define GWA_MOUSE_BUTTON_LEFT      GWA_MOUSE_BUTTON_1
#define GWA_MOUSE_BUTTON_RIGHT     GWA_MOUSE_BUTTON_2
#define GWA_MOUSE_BUTTON_MIDDLE    GWA_MOUSE_BUTTON_3
